/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fileexplorer;
import java.awt.event.*;
import java.awt.event.WindowListener;
import fileexplorer.KoPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import fileexplorer.SubFrameTest;
import java.awt.event.*;
/**
 *
 * @author m
 */
public class MainFrameView extends javax.swing.JFrame implements WindowListener,ActionListener {
    private KoPanel koPanel;
    private SubFrameTest  subFrame = new SubFrameTest();
    DataClassMain dmain;
    /**
     * Creates new form MainFrameView
     */
    private MainFrameView() {
        initComponents();
        
        
        
        dmain = new DataClassMain();
    }
    public MainFrameView(String name)
    {
        initComponents();
        this.setTitle(name);
        this.addWindowListener(this);
        dmain = new DataClassMain();
        koPanel = new KoPanel();
        koPanel.setBackground(Color.ORANGE);
        getContentPane().add(koPanel, BorderLayout.PAGE_START);
        subFrame.setActionListener(this);
        subFrame.setVisible(true);
    }
    public void actionPerformed(ActionEvent e) {
        jTextField1.setText("このいべんとがー\n");
    }
    public void windowClosing(WindowEvent e) {
        textAreaMain.append("closing\n");
    }

    public void windowClosed(WindowEvent e) {
        textAreaMain.append("Closed\n");
    }

    public void windowOpened(WindowEvent e) {
        textAreaMain.append("opend\n");
    }

    public void windowIconified(WindowEvent e) {    
        textAreaMain.append("iconified\n");
    }

    public void windowDeiconified(WindowEvent e) {
            textAreaMain.append("deiconified\n");
}

    public void windowActivated(WindowEvent e) {
        textAreaMain.append("activated\n");
    }

    public void windowDeactivated(WindowEvent e) {
        textAreaMain.append("deactivated\n");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaMain = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        buttonParseTest = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        textAreaMain.setColumns(20);
        textAreaMain.setRows(5);
        textAreaMain.setText("ふるぼっこ\nたまこっぺ\n");
        jScrollPane1.setViewportView(textAreaMain);

        jButton2.setText("おいしそうだねー");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonParseTest.setText("parseTest");
        buttonParseTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonParseTestActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jMenu1.setLabel("ふぁいるっぽい");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setLabel("おわりっぽい");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(buttonParseTest)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(buttonParseTest)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String []stringList = { "いち","２","3"};
        dmain.setSub1Data1("いいちご");
        String tmp = dmain.getSub1Data1();
        textAreaMain.append(tmp);
        dmain.updateSub1Data1();
        for(String s:stringList) {
            textAreaMain.append(s+"\n");
        }
        textAreaMain.append(tmp);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonParseTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonParseTestActionPerformed
        // parse test
        String s = "+32";
        
        try {
            int i = Integer.valueOf(s);
        } catch (Exception e){
            buttonParseTest.setText("parse error");
        }
       
    }//GEN-LAST:event_buttonParseTestActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonParseTest;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea textAreaMain;
    // End of variables declaration//GEN-END:variables
}
